version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - mongo_network

  mongo-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongo-demo
    ports:
      - "8080:8080"
    networks:
      - mongo_network
    depends_on:
      - mongodb


volumes:
  mongo_data:

networks:
  mongo_network:
